# Generated by Django 3.0.8 on 2020-07-31 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusMeetups', '0002_auto_20200731_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetups',
            name='isDeleted',
        ),
    ]
